import { Inter } from "next/font/google";
import "./globals.css";
import Client from "@/components/Client";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crazzy Monster",
  description: "Generated by create next app",
  icons: {
    icons: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Client>
          <Header />
          {children}
        </Client>
      </body>
    </html>
  );
}
