import { Navbar } from "./components/NAvbar";

export const metadata = {
  title: "Crazzy Monster",
  description: "Generated by create next app",
  icons: {
    icons: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navbar />
      {children}
    </div>
  );
}
